// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qedqjkgpasdnxoyutwon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlZHFqa2dwYXNkbnhveXV0d29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjc4OTAsImV4cCI6MjA3MDYwMzg5MH0.dM3KFH94czGGR23okbtTtlSCOSk7Bdcnseffkz5dXMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});